# Generated by Django 4.0.4 on 2022-07-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affecter',
            name='affecter_dte',
            field=models.DateField(auto_now_add=True, db_column='AFFECTER_dte', null=True),
        ),
    ]
