# Generated by Django 4.1 on 2022-08-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_categorie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='categorie_categorie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App.categorie'),
            preserve_default=False,
        ),
    ]
