# Generated by Django 4.0.4 on 2022-07-31 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_affecter_affecter_dte'),
    ]

    operations = [
        migrations.AddField(
            model_name='materieldemande',
            name='equipement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.equipement'),
            preserve_default=False,
        ),
    ]
