# Generated by Django 4.0.4 on 2022-07-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_depense_depense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='materieldemande',
            name='demande_libelle',
            field=models.CharField(blank=True, db_column='DEMANDE_libelle', max_length=100, null=True),
        ),
    ]
