# Generated by Django 4.0.4 on 2022-07-31 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_materieldemande_equipement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='demande_date',
            field=models.DateField(auto_now_add=True, db_column='DEMANDE_date', null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='demande_lien',
            field=models.FileField(blank=True, db_column='DEMANDE_lien', max_length=50, null=True, upload_to='Demandes'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='demande_personel',
            field=models.ForeignKey(db_column='DEMANDE_PERSONEL_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='expediteur', to='App.personel'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='demande_personel_destination',
            field=models.ForeignKey(blank=True, db_column='DEMANDE_PERSONEL_destination', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destiantion', to='App.personel'),
        ),
    ]
