# Generated by Django 4.0.4 on 2022-07-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_materieldemande_demande_libelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materieldemande',
            name='demande_libelle',
        ),
        migrations.AddField(
            model_name='materieldemande',
            name='materiel_demande_libelle',
            field=models.CharField(blank=True, db_column='MATERIEL_DEMANDE_libelle', max_length=100, null=True),
        ),
    ]
