# Generated by Django 4.0.4 on 2022-07-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_materieldemande_demande_libelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='demande_date',
            field=models.DateField(auto_now_add=True, db_column='DEMANDE_date', null=True),
        ),
    ]
