# Generated by Django 4.0.4 on 2022-07-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_demande_demande_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='demande_personel',
            new_name='personel_personel',
        ),
    ]
