# Generated by Django 4.0.4 on 2022-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_demande_personel_demande_personel_personel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartenir',
            name='appartenir_dte',
            field=models.DateField(auto_now_add=True, db_column='APPARTENIR_dte', null=True),
        ),
    ]
